# Generated by Django 4.0.1 on 2022-02-26 14:22

from django.db import migrations, models
import exam.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='image',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to=exam.models.image_save_path),
        ),
    ]
