# Generated by Django 4.0.3 on 2022-04-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_remove_exam_image_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='comment_for_right_answer',
            field=models.CharField(default='Comment', max_length=255, verbose_name='Комментарий для правильного ответа'),
        ),
        migrations.AddField(
            model_name='answer',
            name='comment_for_wrong_answer',
            field=models.CharField(default='Wrong Comment', max_length=255, verbose_name='Комментарий для неправильного ответа'),
        ),
    ]
