# Generated by Django 4.0.3 on 2022-04-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_answer_comment_for_right_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='comment_for_right_answer',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Комментарий для правильного ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='comment_for_wrong_answer',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Комментарий для неправильного ответа'),
        ),
    ]
