# Generated by Django 4.0.4 on 2022-05-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_date',), 'verbose_name': 'Комментарии'},
        ),
    ]
