# Generated by Django 4.0.1 on 2022-02-26 14:22

from django.db import migrations, models
import test.models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_test_image_alter_answer_question_alter_question_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='image',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to=test.models.image_save_path),
        ),
    ]
