# Generated by Django 4.0.1 on 2022-02-18 23:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentgroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('serial_number', models.CharField(max_length=50)),
                ('issued_by', models.CharField(max_length=50)),
                ('inn', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('StudentGroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studentgroup.studentgroup')),
            ],
        ),
    ]
